# Generated by Django 4.2 on 2023-07-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('kun', models.CharField(choices=[('Du-Chorshanba-Juma', 'Du-Chorshanba-Juma'), ('Se-Payshanba-Shanba', 'Se-Payshanba-Shanba')], max_length=50)),
                ('vaqt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.PositiveSmallIntegerField()),
                ('davomiylik', models.CharField(max_length=50)),
                ('dars_narxi', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('tel', models.CharField(max_length=50)),
                ('qayerdan', models.CharField(max_length=50)),
                ('tel2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.CharField(max_length=50)),
                ('xona', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('sigim', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_fan', models.CharField(max_length=50)),
                ('daraja', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kurs')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chegirma', models.PositiveIntegerField()),
                ('summa', models.PositiveIntegerField()),
                ('tolangan_summa', models.PositiveIntegerField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('oy', models.CharField(max_length=30)),
                ('yil', models.PositiveSmallIntegerField()),
                ('admin', models.CharField(max_length=30)),
                ('turi', models.CharField(max_length=30)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.guruh')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.oquvchi')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kurs'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='oquvchilar',
            field=models.ManyToManyField(null=True, to='app1.oquvchi'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ustoz'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.xona'),
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('Keldi', 'Keldi'), ('Sababli', 'Sababli'), ('Sababsiz', 'Sababsiz')], max_length=50)),
                ('sana', models.DateField(auto_now_add=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.guruh')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.oquvchi')),
            ],
        ),
    ]
